# Generated by Django 6.0.7 on 2026-07-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tab', 'Tableau interactif & Affichage dynamique'), ('vis', 'Visioconférence'), ('son', 'Sonorisation'), ('res', 'Réseaux / VoIP'), ('sec', 'Sécurité Informatique & Électronique'), ('acc', 'Accessoires')], max_length=3),
        ),
    ]
